final defaultSearchs = [
  'History',
  'Forestry',
  'Education',
  'Construction',
  'Food \nService',
  'Public \nAdministration',
  'Mining',
  'Retail',
  'Food \nIndustry',
  'Trade',
  'Transport',
  'Labour \nMarket',
  'Real \nEstate',
  'Production',
  'Operations \n Market',
  'Recruitment',
  'Engineering',
  'Hospitality',
  'Consultant',
  'Agriculture',
  'Economics',
  'Technology',
  'Information \nTechnology',
  'Information',
  'Entrepreneurship',
  'Marketing',
  'Robotics',
  'Assistive \nCare',
  'Mechanics',
  'Magic',
  'History',
  'Computer Science',
  'Media',
  'Clothing \nIndustry',
  'Entertainment',
  'Aerospace',
  'Hospitality',
  'Telecommunications',
  'Pharmaceutics',
  'Law',
  'Accounting',
  'Health \nCare',
  'Sales',
  'Communication',
  'Security',
  'Couching',
  'Fashion',
  'Sport',
  'Game \nDesign',
  'Graphics \nDesign',
  'Arts',
  'Medicine',
];
