// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD92JShW8peZLEfAP2KvJKm5O5zuwV1euI',
    appId: '1:724524316630:web:539a2dff480eb1d4dc5677',
    messagingSenderId: '724524316630',
    projectId: 'project-database-b3e2d',
    authDomain: 'project-database-b3e2d.firebaseapp.com',
    storageBucket: 'project-database-b3e2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbv0uJR8Czza-zfW0oNiAAQt1ulbw7qHc',
    appId: '1:724524316630:android:e048f63bec46b773dc5677',
    messagingSenderId: '724524316630',
    projectId: 'project-database-b3e2d',
    storageBucket: 'project-database-b3e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmeo--YfCs-nk99P1XMhU-SK5akcKYI7k',
    appId: '1:724524316630:ios:d23640c04cb909abdc5677',
    messagingSenderId: '724524316630',
    projectId: 'project-database-b3e2d',
    storageBucket: 'project-database-b3e2d.appspot.com',
    iosClientId: '724524316630-u8797hvfo0paefrilfagvinti5bbsd8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmeo--YfCs-nk99P1XMhU-SK5akcKYI7k',
    appId: '1:724524316630:ios:37e89dbda41aa7c8dc5677',
    messagingSenderId: '724524316630',
    projectId: 'project-database-b3e2d',
    storageBucket: 'project-database-b3e2d.appspot.com',
    iosClientId: '724524316630-uvnq4kdi4td82teahuhdh7htk0kc22hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectDatabase.RunnerTests',
  );
}
